#!/usr/bin/env node
var redmine = require('./redmine.js');
var printer = require('./printer.js')

try{
  redmine.connect('http://redmine.org', 'apiKey');
  var projects = redmine.getProjects();
  printer.printProjects(projects.projects);
} catch(err){console.error(err)}
