#!/usr/bin/env node

var unirest = require('unirest');
var Table = require('cli-table');

var table = new Table({
    head: ['ID', 'Tracker', 'Status', 'Priority', 'Assignee', 'Updated']
});

unirest.get('http://redmine.org/issues.json')
.end(function (response) {
  var issues = response.body.issues || [];
  for(var i=0; i<issues.length;i++){
    var issue = issues[i];
    var id = issue.id;
    var tracker = issue.tracker.name;
    var status = issue.status.name;
    var priority = issue.priority.name;
    var assignee;
    if(!!issue.assigned_to)
      assignee = issue.assigned_to.name;
    else
      assignee = '(not assigned)';

    table.push([id, tracker, status, priority, assignee, issue.updated_on]);
  }

  console.log(table.toString());
});
