#!/usr/bin/env node

var program = require('commander');

program
  .version('0.0.1')
  .command('connect [url][api]', 'Connect to server using API key for authentication.')
  .command('projects', 'Display projects.')
  .command('project [key]', 'Display project details.')
  .command('issues', 'Display issue details.')
  .command('issue [id]', 'Display issue details.')
  .parse(process.argv);
